version: '3'
services:
    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        restart: unless-stopped # 컨테이너가 중지되지 않은 경우에만 재시작합니다.
        container_name: mariadb
        # 최대 메모리양 설정 : 128m : 적은양 간단한 작업식 적절
        mem_limit: 128m
        ports:
            - '63100:3306'
        volumes:
            - ./mariadb/maria_data:/var/lib/mysql
            - ./mariadb/sqls/:/docker-entrypoint-initdb.d/
        # 환경 변수 셋팅시에는 `-` 는 생략한다.
        environment:
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_ROOT_PASSWORD: ${DB_PASS}
            TZ: ${TIME_ZONE}
        networks:
            - my-network
networks:
    my-network:
        name: my-network
        driver: bridge
