#!/bin/bash
### BEGIN INIT INFO
# Provides:          uwsgi
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start uWSGI at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
  start)
    echo "Starting uwsgi"
    /app/myvenv/bin/uwsgi -i /app/airbnb-clone/.config/uwsgi.ini &
    ;;
  stop)
    echo "Stopping uwsgi"
    pkill -f uwsgi
    ;;
  restart)
    echo "Restarting uwsgi"
    pkill -f uwsgi
    /app/myvenv/bin/uwsgi -i /app/airbnb-clone/.config/uwsgi.ini &
    ;;
  status)
    if pgrep -x "uwsgi" > /dev/null
    then
      echo "uwsgi is running"
    else
      echo "uwsgi is stopped"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/uwsgi {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0