version: '3'
services:
    webserver:
        build:
            context: ./nginx_webserver
            dockerfile: Dockerfile
        container_name: webserver
        mem_limit: 256m
        restart: always # 컨테이너가 중지될 때마다 항상 재시작합니다.
        volumes:
            - ./nginx_webserver/default.conf:/etc/nginx/conf.d/default.conf
            # nginx log 와 동기화
            - ./nginx_webserver/logs:/var/log/nginx
        ports:
            - '80:80'
            - '3010:3010'
        networks:
            - my-network
networks:
    my-network:
        name: my-network
        driver: bridge
